### ISSUE TITLE
IDL for webrpc schema

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#1]
save this one for v2, but some ideas below.

for v1, we will just use a json file like: https://github.com/webrpc/webrpc-go/blob/master/_example/proto/example.webrpc.json

implementing the schema at https://github.com/webrpc/webrpc-go/blob/master/schema/README.md

note, the data types of webrpc are inspired by protobuf's, Go, TypeScript and WASM :) intended to be serialized as JSON

**Comment by aj0strow** [comment]
What about a documentation style format?

```
TimeInForce
  * GoodForDay = "DAY"
  * GoodTilCanceled = "GTC"
  * FillOrKill = "FOK"

Order
  * ID String
  * TimeInForce TimeInForce
  * Metadata Map(String => Any)

TradingService
  * Submit(Order): String
  * Cancel(String): Boolean
  * Watch([]Symbol): []Boolean
  * Quotes(): Stream(Quote)
```

**Comment by pkieltyka** [comment]
Nice, I really like that idea, that syntax looks great! I’ll see how I can adapt towards that direction

**Comment by pkieltyka** [comment]
here's what i've ended up and am designing for now..

```
service = hello-webrpc
version = v0.0.1

enum Kind: uint32
  - USER = 1
  - ADMIN = 2

message Empty
  -

message GetUserRequest
  - userID: uint64

message User
  - ID: uint64
    * json: id
    * go.tag.db: id

  - username: string
    * json: USERNAME
    * go.tag.db: username

  - createdAt?: timestamp
    * json: created_at,omitempty
    * go.tag.db: created_at

service ExampleService
  - Ping(): bool
  - GetUser(GetUserRequest): User
  - Recv(stream bytes)
  - Send(): stream bytes
  - SendAndRecv(stream bytes): stream bytes
  - Broadcast(): stream Notice
```

**Comment by aj0strow** [comment]
Looking good. What if the top level types match syntax of field types?

```
Kind: uint32
  - USER = 1
  - ADMIN = 2

Empty: message

User: message
  - ID: uint64
    * json: id
    * go.tag.db: id

ExampleService: service
  - Ping(): bool
```

**Comment by pkieltyka** [comment]
could do that too.. but, i like the natural language version you suggested at first.. feels just a bit better

**Comment by pkieltyka** [comment]
done deal. merged in master.

See https://github.com/webrpc/webrpc/blob/master/_examples/hello-webrpc/hello-api.ridl RIDL file for the hello-webrpc example and to generate server/client like so.. 

* `webrpc-gen -schema=hello-api.ridl -target=go -pkg=main -server -out=./api-server/hello_api.gen.go`
* `webrpc-gen -schema=hello-api.ridl -target=js -extra=noexports -client -out=./webapp/client.gen.js`
