### ISSUE TITLE
Telemetry to WebRPC

### ISSUE THREAD

**Issue by OrenLeung** [webrpc/webrpc#100]
Love WebRPC! <3 @pkieltyka 

Is there any way to add telemetry to webrpc? Currently solutions: for example new relic, and open telemetry require context passing by injecting context using their function. If not, can this be added in as a feature? 

## Example Injecting Context OpenTel
![image](https://user-images.githubusercontent.com/47992694/151420925-fb9a1531-9530-4978-ab1b-d04d2539273e.png)

## Example Injecting Context New Relic
![image](https://user-images.githubusercontent.com/47992694/151421036-213d0b8b-a899-43c1-bb3f-f7b93864f2c0.png)
`request = newrelic.RequestWithTransactionContext(request, txn)` right before client.Do(request)

**Comment by pkieltyka** [comment]
hey @OrenLeung sorry for the long time to respond -- did you end up figuring this out?

also, are you wondering about telemtry on the server-side of client-side...? if it is server-side, then you can do this outside of webrpc :) I would recommend using github.com/go-chi/chi in combination, where you setup a telemetry middleware before requests which hit the webrpc service. This is what I do in prod and it works well. You can also set it on the context.Context, which will be passed in via the request context, etc. .etc..

**Comment by pkieltyka** [comment]
see https://github.com/goware/telemetry for some generic middleware for telemetry of net/http services, including webrpc

**Comment by OrenLeung** [comment]
Hi @pkieltyka Thanks for the follow-up! We ended up figuring it out for new relic and open telemetry at CohereAI.

Really appreciate the help!
