### ISSUE TITLE
gen go/ts: rpc methods with no response value

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#105]
presently rpc methods with no response will return a 0 byte body, which is annoying. it should either return an empty object, ie. `{}`, or we return always a response value..

ie.

```
- SomeMethod(in: string)
```
or
```
- SomeMethod(in: string) => ()
```

will cause a 0 byte response body..

for now, the fix is to always return a value.. like `- SomeMethod(in: string) => (ok: bool)` .. and perhaps we should enforce that, but another approach is to just return an empty body which is okay too I think

**Comment by VojtechVitek** [comment]
I think I'd prefer the empty object `{}` response by default.

no return arguments => no fields within the response object

**Comment by pkieltyka** [comment]
Agree, I think empty object `{}` response is the right approach

**Comment by VojtechVitek** [comment]
Fixed in [github.com/webrpc/gen-golang@v0.7.4](https://github.com/webrpc/gen-golang/releases/tag/v0.7.4).
