### ISSUE TITLE
[]*Users vs. []Users

### ISSUE THREAD

**Issue by robfordww** [webrpc/webrpc#106]
This post might me more appropriate for a discussions tab in GitHub, but this project does not have one. My question is if the return type is configurable?  Currently, it seems like all slices of structs/message are mapped to slices of pointers? Is this by design? Any way to create slices of structs instead?

**Comment by pkieltyka** [comment]
hi there,

yes you can do like..

```
message User
  - id: int64
  - address: string
    + go.tag.db = address
    + go.field.type = prototyp.Hash
```

notice the `+ go.XXX` hint? in you case you want to use `+ go.field.type = XXX` and you can override to anything, and the generator will use it.. for example

```
message SomeRequest
   - users: []User
       + go.field.type = []User
```

webrpc v2 is coming out soon too, and has a few more things related to hints as well, lmk how it goes

**Comment by robfordww** [comment]
First thanks for this so useful library!  Great work.
I was in fact aware of that go.field.type feature by reading on this forum, although I didn't consider creating a intermediate message in order to override the return type for the service function.

I have huge respect for your work in Go, so I guess there is a reason for this design. Otherwise, I would prefer a design like this for consistency:


```
message Alarm
 - name: string

service AlarmService
- ListAlarm(q: []string) => (alarms: []Alarm) 
```
results in a function like
`ListAlarms(ctx context.Context, q []string) ([]Alarm)`

```
message Alarm
 - name: string

service AlarmService
- ListAlarm(q: []string) => (alarms: []*Alarm) 
```
results in a function like
` ListAlarms(ctx context.Context, q []string) ([]*Alarm)`

**Comment by pkieltyka** [comment]
the issue is not all languages have pointers, so it wouldn't translate everywhere. To combat that, we add language hints / overrides. We can keep iterating on the schema format in v3, but im eager to get v2 out and in the meantime using code gen hints should work.

As you pointed out, one of the issue is using the code gen hints in the RPC definition itself, as you can't specify `+ go.field.type` there. Luckily v2 solves this in a number of ways you shall see :D

**Comment by ftjfo** [comment]
Can you reveal some info about the timeline for v2?

**Comment by robfordww** [comment]
Can you reveal some info about the timeline for v2?

**Comment by pkieltyka** [comment]
it’s a few weeks away

**Comment by robfordww** [comment]
Kind of hacked it temporarily, while awaiting a nicer solution:

```
{{- else if isStructType $type -}}
    {{$type}}  // USED TO BE: * {{$type}} 
{{- else -}}
    {{if $optional}}*{{end}}{{ get $typeMap $type }}
{{- end -}}
{{- end -}}
```

I have little clue of all consequences of this hack.  But it sure looks to me to generate data structures that are easier to populate with the existing data structures of my database.

**Comment by pkieltyka** [comment]
keep an eye on https://github.com/webrpc/webrpc/pull/123 too -- this introduces webrpc v2 schema with a few changes and a new "alias" keyword
