### ISSUE TITLE
With go1.17+ panic behavior is broken

### ISSUE THREAD

**Issue by jeberly** [webrpc/webrpc#108]
Discovered an issue today when the webrpc handler has code that panic's or you manually add a `panic("stop")` the stack trace is wrong/broken and not helpful in debugging. 

I tested today with one of your example apps, running latest webrpc generator. 

With go1.16 or lower, the panic stack trace looks correct with:

```
 panic: stop
 
 -> main.(*ExampleServiceRPC).GetUser
 ->   /Users/johneberly/go/src/github.com/jeberly/webrpc-golang-basics/main.go:57

    main.(*exampleServiceServer).serveGetUserJSON.func1
      /Users/johneberly/go/src/github.com/jeberly/webrpc-golang-basics/example.gen.go:374
.... <snip>
```

With go1.17 or higher, panic stack trace seems broken:

```
2022/09/28 15:51:06 http: panic serving 127.0.0.1:50847: runtime error: slice bounds out of range [-1:]
goroutine 4 [running]:
net/http.(*conn).serve.func1(0x14000117d60)
	/Users/johneberly/sdk/go1.17/src/net/http/server.go:1801 +0xdc
panic({0x1027e35a0, 0x1400001a210})
	/Users/johneberly/sdk/go1.17/src/runtime/panic.go:1052 +0x2ac
github.com/go-chi/chi/middleware.prettyStack.decorateFuncCallLine({}, {0x1400019c321, 0x21}, 0x1, 0x8)
	/Users/johneberly/go/src/github.com/jeberly/webrpc-golang-basics/vendor/github.com/go-chi/chi/middleware/recoverer.go:130 +0x508
github.com/go-chi/chi/middleware.prettyStack.decorateLine({}, {0x1400019c321, 0x21}, 0x1, 0x8)
... <snip>
```

Steps to reproduce:

1. install and run this example https://github.com/webrpc/webrpc/tree/master/_examples/golang-basics
2. install go version 1.16 via these instructions https://go.dev/doc/manage-install
3. run `go1.16 run .` and then `curl -X POST -H"Content-Type: application/json" -d '{"userID":1234}' http://localhost:4242/rpc/ExampleService/GetUser` and verify 200 response
4. add `panic("stop") to first line in `GetUser` handler, call curl again, verify panic("stop") included in output
5. install go version 1.17 via these instructions https://go.dev/doc/manage-install
6. run `go1.17 run .` and then `curl -X POST -H"Content-Type: application/json" -d '{"userID":1234}' http://localhost:4242/rpc/ExampleService/GetUser` and verify incorrect panic stack trace with `http: panic serving 127.0.0.1:50847: runtime error: slice bounds out of range [-1:]`

Thanks in advance and let me know if I can test anything or I am just missing something.

**Comment by pkieltyka** [comment]
thanks for heads up -- will review + fix soon

**Comment by jeberly** [comment]
Sorry to bump this, we truly appreciate your work on webrpc. But have you been able to verify the problem on your end? Perhaps we are doing something wrong.

**Comment by VojtechVitek** [comment]
I've upgraded the golang-basics example to chi v5 and it works as expected now. See #130

**Comment by geokat** [comment]
Thank you so much!

**Comment by jeberly** [comment]
Thank you!!
