### ISSUE TITLE
webrpc-gen cli v2

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#109]
As part of webrpc v2, I'd like to remove the templates inside of gen/ and instead have them as part of their own repos which would be fetched during the time of code-generation. The webrpc v2 cli would offer just the schema / RPC object tree, and a "gen" sub-package for the methods available for the templates.

Currently in v1 to generate webrpc code we call: `webrpc-gen -schema=example.ridl -target=go -pkg=main -server -client -out=./example.gen.go`

In v2, the `-target=X` flag can receive a uri (assuming https) to a git repo where it would look for `client.tmpl` and `server.tmpl`.

The command would be: `webrpc-gen -schema=example.ridl -target=github.com/webrpc/gen-golang -pkg=main -server -client -out=./example.gen.go`

As a short-hand, we will support `-target=X` as `-target=golang`, `-target=typescript`, etc. and it will by default search https://github.com/webrpc/gen-X for example: https://github.com/webrpc/gen-golang

The logic for parsing the target would be to check for "/", and if we have any "/"'s we assume this is a URI as otherwise it would just be a webrpc-default target which we'll just prepend the "github.com/webrpc/gen-" to the target and continue. Otherwise we will use the remote target.

This will be really cool because anyone can fork a generator and tweak it as they like, it it would be very easy for them to add new support for another language.

----

TODO
- [ ] Add remote git support for -target flag
- [ ] Pull/fetch git repos remotely, and also cache them locally somewhere, perhaps in ~/.webrpc/
- [ ] Update webrpc/gen package to use a well-defined set of function maps used by the templates
- [ ] Copy golang/typescript/javascript templates and push to respective new repos under github.com/webrpc/gen-XXX

**Comment by ftjfo** [comment]
Would it make sense to do `-taget=./tmpldir` and be able to target own custom templates without invoking a git command.  Or am I supposed to recompile the `webrpc-gen` binary in those cases?  For instance, one might want to an alternative to the hard-coded `/rpc path` or similar.

**Comment by pkieltyka** [comment]
Definitely. -target=<localpath> pointing at a directory of templates should also be valid

**Comment by pkieltyka** [comment]
Done and tagged v0.6.1
