### ISSUE TITLE
Possible error in Typescript definitions

### ISSUE THREAD

**Issue by robfordww** [webrpc/webrpc#135]
Using the latest versions (as far as I know), this RIDL:
```
message Comments
	- ID:      int64
	- AlertID: int64
```

results in  Go code like:

```
type Comments struct {
	ID      int64     `json:"iD"`
	AlertID int64     `json:"alertID"`
```

in typescript it looks like this (notice the casing):
```
export interface Comments {
  ID: number
  AlertID: number
```

The problem is that typescript interface does not match the json stream, so that` x.AlertID `gives nil, but` x.alertID` gives the right data, though is invalid according to typescript.

Is this intended behavior?

**Comment by pkieltyka** [comment]
good catch.. there is definitely a bug here
