### ISSUE TITLE
Proposal: Remove "json" meta for webrpc@v2

### ISSUE THREAD

**Issue by VojtechVitek** [webrpc/webrpc#141]
I propose we remove the `+ json = {CUSTOM_JSON_FIELD_NAME}` meta for webrpc v2.

JSON is the core of webrpc and thus I don't see why we'd need different field names in RIDL vs. in JSON.

### 1. Field names over the wire (JSON)
Instead of being able to "overwrite" RIDL field names with `json` meta, why don't we simply rely on the RIDL field name itself?

Example:
```
struct User
  - id: uint64
  - FIELD_name: string
```
would send
```
{ "user": {"id": 0, "FIELD_name": ""} }
```

### 2. Custom field names in TypeScript/JavaScript
- not supported (aka, same as with `json` meta)
- RIDL field name is what you see in JSON, and what you get in TS/JS

###  3. A special `+ json = -` value
See https://github.com/webrpc/webrpc/issues/66 for a related bug report about `+ json = -`

I believe this special value was added because of Go's `json:"-"` struct tag, which means "hide" this field in JSON. I think it could be replaced by some new option to "hide" server fields from the API clients.

Example:
```
struct User
  - id: uint64
  - FIELD_name: string
  - privateID: string
    + private = true
```
would still send
```
{ "user": {"id": 0, "FIELD_name": ""} }
```
since the `privateID` field was "hidden", it would not make it to the generated code for clients. However, the generated server code would still have the `privateID` field available (Go, Node.js or any other server).

**Comment by c2h5oh** [comment]
Counter argument: You already have the behavior you want if you don't use json meta and having the extra flexibility is nice.

Example uses: 
- not forcing capitalized field names just because golang requires them to be public - yes you could override name just for golang, but how is it different from overriding it just for json?
- following conflicting coding guidelines (camel case in golang, snake_case in js for example) - useful when porting things.

As for `private` meta I would prefer `serverOnly` to make it clear that the restriction is limited to clients.

**Comment by VojtechVitek** [comment]
Thanks for good feedback, @c2h5oh.

> not forcing capitalized field names just because golang requires them to be public

Golang generator already handles capitalization of the first letter for Go field names, no matter how the JSON field name looks like over the wire.

>  yes you could override name just for golang, but how is it different from overriding it just for json?

My thinking was that JSON field feels redundant to me. It changes not only how JSON looks over the wire, but also how fields are named in JS/TS.

Do you like camel_case? Why don't you use that in RIDL? Do you prefer PascalCase? Use that in RIDL too :)

Do you like some other text case naming convention for Go only? Perhaps the Golang generator could have [a new option](https://github.com/webrpc/gen-golang#set-custom-template-variables) to override the naming style for you.

But I hear you, the `json` meta is optional. But I'm still not convinced we really need it.

"Less is exponentially more."

> As for private meta I would prefer `serverOnly`

agreed, that's a better name for sure

**Comment by c2h5oh** [comment]
> My thinking was that JSON field feels redundant to me. It changes not only how JSON looks over the wire, but also how fields are named in JS/TS.

Well, JSON stands for Java Script Object Notation, I kind of expect it to affect JS/TS. If you want separation of concerns here then maybe the change should be to add `js.field.name` / `ts.field.name` etc support.

> Do you like some other text case naming convention for Go only? Perhaps the Golang generator could have [a new option](https://github.com/webrpc/gen-golang#set-custom-template-variables) to override the naming style for you.

I can't see that not being both hard to implement and pain to use if you want to specify overrides for specific names.
