### ISSUE TITLE
Proposal: webrpc-gen CLI v3

### ISSUE THREAD

**Issue by VojtechVitek** [webrpc/webrpc#153]
Generate multiple targets in parallel from a single `webrpc-gen` command.

Usage: `webrpc-gen <schema.(ridl|json)> <target> [-targetOpts...] ... [<targetN> [-targetNOpts]...]`

Example:
```
webrpc-gen schema.ridl \
  golang -server -pkg server -out ./server/server.gen.go \
  golang -client -pkg client -out ./client/client.gen.go \
  typescript -client -out ../frontend/src/client.gen.ts \
  openapi -out ./openapi.yaml
```

- Opt-in feature
    - users can still execute one target only
    - we can support `-schema=` and `-target=` flags for backward compatibility
- Faster execution
     - parses RIDL/JSON only once for multiple targets
     - downloads and executes all target templates in parallel
- Arguably more readable

**Comment by pkieltyka** [comment]
I find this to be more confusing, and I’m not sure why it would be much faster once a cache is in place after first invocation. I do find exec between calls to be slow, and maybe this is an optimization we can make in the remote fetch code
