### ISSUE TITLE
poor code generation: error helpers expanding strings unexpectedly

### ISSUE THREAD

**Issue by vgough** [webrpc/webrpc#154]
Some of the generated error helpers take non-interpreted parameters and then pass them to a variadic helper which interprets the parameters. 

For instance: 
```go
func ErrorInvalidArgument(argument string, validationMsg string) Error {
	return Errorf(ErrInvalidArgument, argument+" "+validationMsg)
}
```

If the validation message contained any printf-style % interpreted variables, then Error would try to interpret them even though the signature for ErrorInvalidArgument doesn't allow for any parameter expansion.

The generated code shouldn't call Errorf for argument expansion.

**Comment by pkieltyka** [comment]
The upcoming release changes error handling completely. Stay tuned :)
