### ISSUE TITLE
Github limit reached

### ISSUE THREAD

**Issue by alinz** [webrpc/webrpc#160]
Hello old friends, 
I have been using webrpc for a couple of projects now, and it works fantastic, but recently I have been having an annoying error from github action during the build process.

```
failed to load templates from git github.com/webrpc/gen-golang: failed to load templates from
remote git repository github.com/webrpc/gen-golang: get git repository: 
GET https://api.github.com/repos/webrpc/gen-golang: 403 
API rate limit exceeded for 40.77.123.112. 
(But here's the good news: Authenticated requests get a higher rate limit. Check out the 
documentation for more details.) [rate reset in 1m42s]
```

This is not an issue with this awesome tool, but rather DX issue. Is there any way, we could vendor the templates by using webrpc-gen command so they can be committed to my repo? Like adding a new flag `--vendor` which downloads the content.

By the way, I know I can clone the templates and manually put them in my repo, but it would be cool and very valuable if the cli can do that for me.

Thanks for this amazing tool. 👍

**Comment by pkieltyka** [comment]
hey Ali :) nice to hear from you pal.

That's cool you're using webrpc in your proejcts. We have some very nice updates coming soon around errors.

Did you manage to figure out your rate-limiting issue..? We don't want to vendor templates as we want to keep webrpc-gen just a simple cli and pull from any template source. We do have caching built-in on fetching though, so that should help.

**Comment by VojtechVitek** [comment]
Hi Ali 🎉 ,

I think this was resolved in https://github.com/webrpc/webrpc/pull/165.

Try webrpc-gen@v0.10.0 ;)

**Comment by alinz** [comment]
@pkieltyka @VojtechVitek Nice to hear from you guys,
rate limiting issue was fixed once I upgraded to 0.10.0.

I just got a different error message and it prevents me from moving forward with my project
Here is the error message:

>generating golang code
```
webrpc-gen -schema=schema/rpc.ridl -target=golang@v0.10.0 -pkg=rpc -server -client -out=internal/rpc/rpc.gen.go
        command failed: failed to load templates from github.com/webrpc/gen-golang@v0.10.0: failed to parse templates: vfs/text/vfstemplate: pattern matches no files: `/*.go.tmpl`
```     

> generating typescript code
```
webrpc-gen -schema=schema/rpc.ridl -target=typescript@v0.10.0 -client -out=app/src/api/api-gen.ts
        command failed: failed to load templates from github.com/webrpc/gen-typescript@v0.10.0: failed to parse templates: vfs/text/vfstemplate: pattern matches no files: `/*.go.tmpl`
make: *** [webrpc] Error 1
```

p.s By the way, do you have a public slack or discord so I can join and ask all my questions about this project? or do you want me to keep posting here as a separate issue?

**Comment by VojtechVitek** [comment]
@alinz thanks for reporting this. Would you mind submitting a new issue with more details including `webrpc-gen -version` / OS / architecture? I can't reproduce this myself. And the CI pipeline, which runs these commands too, is happy too :)

Currently we don't have any Slack/Discord. Might make sense to create a webrpc channel in Golang Slack?

**Comment by VojtechVitek** [comment]
@alinz can you please try to get me the reproducer? Did you build the webrpc-gen yourself?

I've just created #webrpc channel on Golang Slack. Feel free to join ;)

**Comment by pkieltyka** [comment]
@alinz please don’t submit tickets if you’re not willing to respond with additional info. Otherwise, next time will just ignore your messages.
