### ISSUE TITLE
Proposal: Accept io.FS in RIDL/JSON schema parsers

### ISSUE THREAD

**Issue by VojtechVitek** [webrpc/webrpc#173]
Currently, the RIDL and JSON parsers accept `io.Reader` to read the initial schema file but then they reach out to the OS filesystem when an import is found.

This is a side-effect that can't be tested easily in the unit tests. That's why we have `enableMockImport()` and `disableMockImport()` helpers that change the `ridl` package behavior to enable unit tests with disabled import resolution. This is a global `ridl` package side effect -- all the tests must be run serially.

### Proposal: Update RIDL/JSON schema parsers to accept io.FS filesystem with an entry-point file path
`proto, err := ridl.Parse(fs, "api.ridl)`

- This will allow better parser errors (having `file:line`).
    - See `func (p *Parser) trace(err error, tok *TokenNode) error`
- This will allow easy unit testing via `testing/fstest` package.
    ```
    m := fstest.MapFS{
       "api.ridl": {
          Data: []byte("import types.ridl"),
       },
       "types.ridl": {
          Data: []byte("struct Imported"),
       },
    }
    ```
- This may enable us to import remote filesystems in the future (`import github.com/webrpc/types/page.ridl`).

**Comment by pkieltyka** [comment]
Great idea
