### ISSUE TITLE
json-rpc 2.0 -- should we use it?

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#2]

**Comment by shazow** [comment]
IMO default should be "yes", and otherwise justified. ;)

**Comment by nkev** [comment]
I would suggest OpenAPI 3.0. There are Go libraries for it already, like https://github.com/getkin/kin-openapi

**Comment by pkieltyka** [comment]
thanks @nkev but for this, we're just thinking of a data structure convention for including metadata in a req/resp. openapi provides much more than that. See https://www.jsonrpc.org for more info.

**Comment by nkev** [comment]
I know. Why wouldn't you make your JSON schema compatible anyway and not re-invent the wheel?

**Comment by pkieltyka** [comment]
Reinvent which wheel? We don’t use json-rpc, we don’t have a need for any schema in the payload at the moment. If I add streaming/websocket support, then will need it, and most likely will adopt json-rpc 2 then

**Comment by pkieltyka** [comment]
don't need it
