### ISSUE TITLE
Proposal: add Support for Enum strings

### ISSUE THREAD

**Issue by klaidliadon** [webrpc/webrpc#203]
I suggest to add the possibility of defining enum of strings. 

```
enum ItemCode: string
  - codeItemOne = "item_1"
```

The changes required are:

- Allowing the int type in the schema:
https://github.com/webrpc/webrpc/blob/664a6c1261bc948e0517f25c533e3f74353282e8/schema/type.go#L100-L102
		Would become:

	```go
	if f := fieldType.String(); !isValidVarType(f, VarIntegerCoreTypes) && !isValidVarType(f, []CoreType{T_String}) {
		return fmt.Errorf("schema error: enum '%s' field '%s' is invalid. must be an integer or a string type", t.Name, f)
	}
	```

- changing generation of key for strings:
https://github.com/webrpc/webrpc/blob/664a6c1261bc948e0517f25c533e3f74353282e8/schema/ridl/ridl.go#L187-L190
We add a behavior that sets the value to a quoted string that use the value or key, if there's no value.
	```go
	switch enumDef.Type.Type {
	case schema.T_String:
		if def.Right().IsInvalid() {
			val = key
		}
		val = fmt.Sprintf("%q", val)
	default:
		if val == "" {
			val = strconv.Itoa(i)
		}
	}

	```	
- We can also add validation on the templates from:
	```
	func (x {{$name}}) MarshalJSON() ([]byte, error) {
		buf := bytes.NewBufferString(`"`)
		buf.WriteString({{$name}}_name[{{$type}}(x)])
		buf.WriteString(`"`)
		return buf.Bytes(), nil
	}
	```
	To:
	```
	func (x {{$name}}) MarshalJSON() ([]byte, error) {
		v, ok := {{$name}}_name[{{$type}}(x)]
		if !ok {
			return nil, fmt.Errorf("invalid %T value: %v", x, x)
		}
		buf := bytes.NewBufferString(`"`)
		buf.WriteString(v)
		buf.WriteString(`"`)
		return buf.Bytes(), nil
	}
	```

**Comment by VojtechVitek** [comment]
@klaidliadon can you post the whole RIDL example (with both the existing ENUM and the proposed ENUM), please?

**Comment by pkieltyka** [comment]
good idea on this feature!

**Comment by klaidliadon** [comment]
My issue was that the enum are saved as int in the database, which forces you to append new values and is also not intuitive when you are looking at the db directly.

I now think that this is the wrong place to address that. It's easier to just use `enumValue.String()` when saving in the database. If you agree, we can close this.

**Comment by LukasJenicek** [comment]
@klaidliadon 

Personally I don't feel that saving string instead of int8 to database is a good idea. We would need to define it as `enum` on the database level as well which would force us to write database migration for any change.

**Comment by VojtechVitek** [comment]
Agreed.

We don't want to save ENUM string values into a DB even though they're more readable than integers. Postgres supports ENUM type for strings (https://www.postgresql.org/docs/current/datatype-enum.html) but that would mean we'd have to maintain the values via DB migrations.

I think we should keep integer-only ENUMs for now.

**Comment by pkieltyka** [comment]
hey guys -- we definitely want enum string support / complete this ticket.

webrpc is used to describe a schema of data and help build runtime types. There are a few times when we want to specify an enumeration of labels (aka enum strings).

On Sequence side, its come up a lot:
1. analytics, enumerating the string of event names -- we do not want to be using numbers, as the source expects strings. Please remember, not everything we do with webrpc is to store data in a db or send something over rpc, we use it as the runtime schema of data for everything
2. waas "intent" label names.. its a lot for me to write, but me saying, we need it.

I think where it becomes even more useful is on the typescript side, but we need to make sure both Go and TS support both forms, as again, it comes up a lot.

definitely lets queue it for completion.

**Comment by LukasJenicek** [comment]
Done by: 
Gen-Golang: https://github.com/webrpc/gen-golang/pull/53
Webrpc: https://github.com/webrpc/webrpc/pull/247
