### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by ftjfo** [webrpc/webrpc#204]
Regarding the example in `https://github.com/webrpc/webrpc/tree/master/_examples/hello-webrpc/server`

The statement:
`return nil, ErrorNotFound("unknown userID %d", 911)`  is written in `main.go`, but no such function seems present in the generated code `hello_api.gen.go`

**Comment by LukasJenicek** [comment]
This should be fixed by this pull request: https://github.com/webrpc/webrpc/pull/209
