### ISSUE TITLE
add support for @latest tag name for generators

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#213]
with commands like,

`//go:generate go run github.com/webrpc/webrpc/cmd/webrpc-gen -schema=databeat.ridl -target=golang -pkg=proto -server -client -out=./databeat.gen.go`

the `-target=golang` will use the master head of the gen-golang templates. At time of writing, this would be `v0.12.x-dev`

I'm proposing to add `-target=golang@latest` which would use the latest tagged version. At time of writing, the latest tagged version for gen-golang is `v0.11.0`

**Comment by VojtechVitek** [comment]
I agree with the proposal.

On top of that, I think we should make `-target=golang` more stable. Perhaps, as in Go, it would also download the latest tagged version.

```
-target=golang # latest tag
-target=golang@latest # latest tag
-target=golang@v0.11.0 # specific tag
-target=golang@master # master branch
-target=golang@some_other_branch # PR branch
```

Or even better, I propose we `//go:embed` the latest stable `github.com/webrpc/gen-*` generators into webrpc-gen binary. This way we could guarantee the stability and interoperability of the default targets.

```
-target=golang # stable and tested tag embedded into webrpc-gen, ie. v0.11.2
-target=golang@latest # fetch latest tag
-target=golang@v0.11.0 # fetch specific tag
-target=golang@master # fetch master branch
-target=golang@some_other_branch # fetch PR branch
```

for non-`github.com/webrpc/gen-*` repositories, the default would be the same as `@latest` tag

**Comment by VojtechVitek** [comment]
As of https://github.com/webrpc/webrpc/pull/26, the `-target=golang` now uses the `//go:embed`ed version of the [golang](https://github.com/webrpc/gen-golang) template, pinned at specific version in go.mod file: https://github.com/webrpc/webrpc/blob/a3fb4fd91beb76e8f980b04137f416fd478fc575/go.mod#L18

**Comment by VojtechVitek** [comment]
Closing per last comment.

`-target=golang` now uses embedded version of the generator that was tagged & tested with webrpc-gen
