### ISSUE TITLE
add -service=XX cli flag to only perform gen on specific service and related types

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#215]
it would be useful for client generation, and server generation too in some cases, to pass `-service=API` where "API" is the `service API` name in a webrpc schema and it would only include the code-gen of types and interfaces which are used by the "API" service rpc methods.

this is useful so you can have a schema with both "API" and "Admin" service, and generate a public client for just the "API" and a separate internal client for the "-service=API,Admin" with both, or just omit -service for standard generation of all, or admin only as `-service=Admin`

**Comment by LukasJenicek** [comment]
Implemented and released in `v0.20.1` version. 

See: https://github.com/webrpc/webrpc/releases/tag/v0.20.1
