### ISSUE TITLE
Use Comments in code generation

### ISSUE THREAD

**Issue by klaidliadon** [webrpc/webrpc#246]
It would be very helpful to be able to parse comments block before enums, structs, structs fields, and even methods and use them as properties of such types.

For instance:
```
# SessionType is the authentication level of a session
enum SessionType: int8
  - USER
  - ADMIN

# User is a user of the application
struct User
# ID is a UUID v4
- id: string
```

This has comment for enum, struct and a struct field. If those would be parsed and added in a property of the schema, we could use it when generating code:

```go
// User is a user of the application
type User struct {
  // ID is a UUID v4
  ID string 
}
```

It could be a good way of document a ridl and at the same time it would allow to use it as go doc and editor suggestions.

**Comment by VojtechVitek** [comment]
Sounds like a great idea :)

**Comment by pkieltyka** [comment]
I think this is a great idea. We should add a `Comment string` on the schema objects going down the entire tree. For example, each type, field, service, rpc method, argument, etc. etc. etc... everything should have a `Comment: string` and when we parse, anything above the definition would be included as a comment (including multi-lines)

**Comment by taylanpince** [comment]
Just piling on here, I love this. We can also leverage it in openapi file generation for endpoint summaries as `description` generator

**Comment by klaidliadon** [comment]
It would be great to have comments for a method and its arguments:
```
```

**Comment by VojtechVitek** [comment]
Implemented in https://github.com/webrpc/webrpc/pull/252 and https://github.com/webrpc/webrpc/pull/258
