### ISSUE TITLE
Custom schema error is not generated when imported

### ISSUE THREAD

**Issue by jmho** [webrpc/webrpc#303]
I am working on a project and am loving using webrpc so far! 

Currently, I am using imports to break up and organize my `ridl` files. The convention I've been using is a `main.ridl` that imports all of the other `ridl` files to be generated. I've noticed that for all imported files, everything except the custom schema errors are generated in the output after running the `webrpc-gen` cli.

I can get around this by moving all my custom errors to the `main.ridl` but this is not super ideal organizationally. I have attached a reproduction project [here](https://github.com/jmho/web-rpc-example). Please let me know if this is intended behavior and apologies if I missed anything. Thanks!

**Comment by VojtechVitek** [comment]
Thanks for the report, @jmho :)
