### ISSUE TITLE
ridl polish

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#35]
- [x] gen/golang -- make sure to generate json struct tags always, even if we don't define them in meta

- [x] gen/golang -- add go.tag.json override, might already work for free..

- [ ] enum error message is on wrong line -- `enum Blah` which misses `: type` should error on that line .. or set a default of uint32

- [x] bug, defining dupes of messages in RIDL, doesnt return an error? 
   * ie. message Blah; - x: string; message Blah; -x: string

**Comment by VojtechVitek** [comment]
I've just tested enum error and it prints a correct line

```
68: enum Blah
69:  - BLAH
 ```
 
 ```
 failed to parse api.ridl:68:4: error near "enum": expecting "[colon]", got "\n"
 ```
