### ISSUE TITLE
Approach to documentation generator?

### ISSUE THREAD

**Issue by jeberly** [webrpc/webrpc#37]
First off, huge thanks to this library!! It looks like exactly what I was looking for after evaluating Twirp, et al. I love that it is simple, and right to the point with little dependencies and easy to grep the source. Keep up the good work. 

Although RIDL is fairly self documenting (good job), has there been any thought into a doc generator with outputs eg. swagger, etc?  Just interested in your thoughts/recommendations as I was thinking about potentially writing a generator to build docs we could publish for our API.

**Comment by pkieltyka** [comment]
thanks @jeberly :) really appreciate your enthusiasm, let me know if you guys actually try webrpc and how it works out for ya.

a doc generator is a great idea, and would be totally possible and could hook into the gen tools :) ie. instead of outputting ts/js/go/etc source -- generate docs

**Comment by pkieltyka** [comment]
See https://github.com/webrpc/gen-openapi :)

**Comment by VojtechVitek** [comment]
FYI, I recommend using https://github.com/webrpc/gen-openapi/tree/v0.6.0 tag.

I'm still iterating on the openapi generator and future webrpc-gen API and so the `master` branch is quite unstable right now.

**Comment by VojtechVitek** [comment]
There's more documentation now at https://github.com/webrpc/gen-openapi#generate-openapi-3x-yaml-file.

You can build a static HTML documentation or use Swagger UI / Editor.
