### ISSUE TITLE
Error handling in js/ts generated code

### ISSUE THREAD

**Issue by paulxuca** [webrpc/webrpc#38]
```
export interface WebRPCError extends Error {
  code: string;
  msg: string;
  status: number;
}

export const throwHTTPError = (resp: Response) => {
  return resp.json().then((err: WebRPCError) => {
    throw err;
  });
};
```

This is all fine and dandy, but if the response is anything that isn't json serializable, this causes an error to be thrown when calling `resp.json()`. I think a more suitable method of handling an error would be to first attempt json deseraialization, and then if it throws an error, throw a new error with either the response body/ status code.

**Comment by pkieltyka** [comment]
agreed -- but the server should always return something deserializable, or have you seen in practice otherwise? ie. worst case you'd get back `""` 

lmk

**Comment by paulxuca** [comment]
Cloudflare 503 is a full on HTML page, which is how I ran into this issue

**Comment by pkieltyka** [comment]
gotcha, makes sense. would you mind submitting PR of updated TS template for the additional deserialization check + throw
