### ISSUE TITLE
is type Uint64 and Int64 safe for javascript?

### ISSUE THREAD

**Issue by alinz** [webrpc/webrpc#48]
Currently javascript engine which parse JSON does not support Int64 and Uint64 and it may overflow and represent a wrong value. Have you thought about this issue?

**Comment by pkieltyka** [comment]
hey @alinz thanks for bringing up the issue. The standard says the number type ranges from - 2^53 - 1 to 2^53 - 1 which you're right won't fit into uint64 -- but, in my chrome console I can represent a number far larger then those rangers which I'm not sure how that works. However, if we must, we can use a string type under-the-hood, or rename the webrpc type from uint64 to uint53 (just kidding)

**Comment by alinz** [comment]
Sounds good, I just wanted to have this documented here. I will close this for now.

**Comment by pkieltyka** [comment]
It’s def an important issue that leaves me a bit confused but number ranges seem to work, perhaps that is off-standard tho
