### ISSUE TITLE
whitespace in RIDL file causes `webrpc-gen` to hang indefinitely.

### ISSUE THREAD

**Issue by jeberly** [webrpc/webrpc#51]
If there is any whitespace chars on a blank line in `.ridl` file, it causes `webrpc-gen` to just hang and churn CPU, never exiting.

You can recreate by adding a space to line 2 of https://github.com/webrpc/webrpc/blob/master/_examples/hello-webrpc/hello-api.ridl

and try to run `make generate`.

in case it matters.  I was running on macOS 10.14.5.

**Comment by pkieltyka** [comment]
indeed you are right! what a strange one. I'll fix this in a few

**Comment by xiam** [comment]
Fixed. Thanks for spotting this one @jeberly.
