### ISSUE TITLE
"time" imported but not used error - in the generated golang server file

### ISSUE THREAD

**Issue by pongsanti** [webrpc/webrpc#52]
BTW. Thank all you guys for creating the go-chi. :smiley: I really like the minimalist vibe of it.

I don't have any messages with `time.Time` type in my `ridl` file, but `time` is imported anyway.

The ridl file
https://gist.github.com/pongsanti/6c38c1d28bb41c70d6d639b1e05657b1#file-schema-ridl

command:
`webrpc-gen -schema=schema.ridl -target=go -pkg=main -server -out=./schema.gen.go`

The generated file
https://gist.github.com/pongsanti/6c38c1d28bb41c70d6d639b1e05657b1#file-schema-gen-go

**Comment by pkieltyka** [comment]
resolved in https://github.com/webrpc/webrpc/commit/6e3fe87a082daccd5cf06d734ae378948495896a
