### ISSUE TITLE
Provide method to return webrpc style errors from middleware

### ISSUE THREAD

**Issue by geokat** [webrpc/webrpc#54]
In the same vein as https://github.com/twitchtv/twirp/issues/161

**Comment by geokat** [comment]
As a workaround, using the generated `writeJSONError` method works as long as the generated package name (in Go) is the same as the middleware one.

**Comment by pkieltyka** [comment]
hey @geokat in my services, I added this extra method in my middleware package:

```go
func middlewareError(w http.ResponseWriter, rpcErr proto.Error) {
	statusCode := proto.HTTPStatusFromErrorCode(rpcErr.Code())
	respBody, err := json.Marshal(rpcErr.Payload())
	if err != nil {
		panic(err.Error())
		return
	}

	w.WriteHeader(statusCode)
	w.Header().Set("Content-Type", "application/json")
	w.Write(respBody)
}
```
which I then use to return an error from my middlewares. Alternatively though, as I look at this [writeJSONError() method](https://github.com/webrpc/webrpc/blob/master/_examples/hello-webrpc-ts/server/hello_api.gen.go#L338-L360), we can probably drop the ctx argument and export this method

**Comment by pkieltyka** [comment]
thanks @geokat for the suggestion. I've included the `RespondWithError(w, err)` method. Just update webrpc-gen, and run the generator again to get the latest code-gen output with this method, enjoy

**Comment by geokat** [comment]
Thanks so much!

**Comment by VojtechVitek** [comment]
For reference, the above helper function is available in the generated code for some time: `proto.RespondWithError(w, err)`.
