### ISSUE TITLE
gen/go: field of enum type should not be a pointer type in gen'd code

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#55]

**Comment by 1vn** [comment]
One workaround is to override the pointer type by specifying go.field.type:
```
  - type: UserType
    + go.field.type = UserType
```

Note, if you use this as a service parameter (i.e. `UpdateUserType(userID: int64, type: UserType`) the service interface will still expect a pointer arg for the enum

**Comment by LukasJenicek** [comment]
Done by: https://github.com/webrpc/gen-golang/pull/53
