### ISSUE TITLE
Set cookie w/ via webrpc handler and generated typescript client?

### ISSUE THREAD

**Issue by jeberly** [webrpc/webrpc#56]
Any advice/ideas on how to set a cookie via a webrpc handler when the generated typescript/javascript code calls an endpoint?   Eg. `api.Login()` on success sets a browser cookie.

**Comment by pkieltyka** [comment]
@jeberly sure thing --

inside of a webrpc rpc handler, you can grab the *http.Request and http.ResponseWriter from the `ctx` argument like so..

```go
	w, _ := ctx.Value(proto.HTTPResponseWriterCtxKey).(http.ResponseWriter)
	r, _ := ctx.Value(proto.HTTPRequestCtxKey).(*http.Request)
	http.SetCookie(w, &cookie)
```

**Comment by pkieltyka** [comment]
And btw, proto in the example above is the name of my package that has the webrpc-gen’d server code

**Comment by jeberly** [comment]
Thank you!
