### ISSUE TITLE
streaming support

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#58]
I've spent a lot of time thinking about a suitable design to support streaming support for webrpc that will also work with browsers.

The approach is to use chunked transfer encoding for request or response bodies to handle streaming, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

As for RIDL support, it could look like below:

```
service ApiService
  - Ping() => (status: bool)

  # streaming request body, single response
  - stream Upload(base64: string) => (status: bool)

  # single request, streaming response body
  - Download(file: string) => stream (base64: string)

  # steaming request body and response body,
  - stream Bidirection(msg: string) => stream (msg: string)
```

this is a slight difference from what is currently implemented, which looks like

`- Download(msg: string) => (msg: stream string)` 

however, moving stream at the front of input or output definition is the better approach since the entire request or response payload would need to be streamed.

as for the update to the schema, the `schema/service.go` structure should change to..

```go
type Service struct {
	Name    VarName   `json:"name"`
	Methods []*Method `json:"methods"`

	Schema *WebRPCSchema `json:"-"` // denormalize/back-reference
}

type Method struct {
	Name    VarName           `json:"name"`
	Stream  string            `json:"stream"` // "input", "output", "input-output"
	Inputs  []*MethodArgument `json:"inputs"`
	Outputs []*MethodArgument `json:"outputs"`

	Service *Service `json:"-"` // denormalize/back-reference
}

type MethodArgument struct {
	Name     VarName  `json:"name"`
	Type     *VarType `json:"type"`
	Optional bool     `json:"optional"`

	InputArg  bool `json:"-"` // denormalize/back-reference
	OutputArg bool `json:"-"` // denormalize/back-reference
}
```
notice that `Stream` moved from `MethodArgument` to `Method`. As well, its defined as a string now, with values of "input", "output" or "input-output" to define the pipes that support streaming for the method.

as for implementation for Go server/client, or other languages a few notes:

1. Browsers buffer the first 1kb of chunked response, see https://gist.github.com/CMCDragonkai/6bfade6431e9ffb7fe88 -- a good idea is then to send 1024 bytes of random data, and make sure client is aware of that to omit it

2. `0\r\n\r\n` defines the terminal signal that the chunked body is at EOF

3. For response streaming, it's good practice to send `\r\n` every 10 seconds or so to keep connections alive, and clients to support this 

For the Go implementation, the interface for above methods could be..

```go
type ApiService interface {
  Ping(ctx context.Context) (bool, error)
  Upload(ctx context.Context, stream UploadReader) (bool, error)
  Download(ctx context.Context, file string) (DownloadWriter, error)
}
```

```go
type UploadReader interface {
  Done() <-chan struct{}
  Read() (UploadRequestBody, error)
}

type DownloadWriter interface {
  Done()
  Write(v DownloadResponseBody, err error) error
}

type DownloadResponseBody struct {
  Base64 string `json:"base64"`
}
```

**Comment by pkieltyka** [comment]
btw, @xiam just a small note when you're working on the lexer about the correction above..

before:
`- Method(msg: stream string) => (msg: stream string)`

after:
`- stream Method(msg: string) => stream (msg: string)`

the reason for this change is there could be methods like ..

`- stream Method(index: uint64, filter: string) => stream (t: time, data: string)`

where the req/resp payloads look like ..

req: `{ "index": 1, "filter": "hi" }` resp: `{ "t": 1, "data": "........" }`

**Comment by VojtechVitek** [comment]
Implemented since https://github.com/webrpc/webrpc/releases/tag/v0.17.0. Example: https://github.com/webrpc/webrpc/tree/master/_examples/golang-sse
