### ISSUE TITLE
Tag value with colons and parenthesis doesn't parse anymore

### ISSUE THREAD

**Issue by hooksoft** [webrpc/webrpc#60]
Hi,
I've been evaluating this project and noticed that this kind of tag value doesn't parse anymore:

```
    - CreatedAt: timestamp
        + go.tag.pg = default**:**now**()**,use_zero
```
The code seems to be: 

https://github.com/webrpc/webrpc/blob/3a0c9f0ee2f9eeda68b5fade4454c1a11791e94b/schema/ridl/parser.go#L342

and gives

`parse error: "unexpected token" near ":" (line: 14, col: 30)`

**Comment by pkieltyka** [comment]
Thanks for the report. What version of webrpc are you using? Master? We can surely fix this one easily

**Comment by hooksoft** [comment]
I think so: commit `3a0c9f0ee2f9eeda68b5fade4454c1a11791e94b` from `Tue Nov 12 10:05:45 2019 -0600`

**Comment by hooksoft** [comment]
BTW thank you so much for webrpc.  I hope I can deploy it soon :)

**Comment by pkieltyka** [comment]
@hooksoft :) np.

ah yes I see. My suggestion in the near term is to install an older commit of webrpc until we fix this issue. It seems to be a bug we introduced with the latest lexer cc: @xiam

**Comment by pkieltyka** [comment]
I have to double check, but I believe the issue is here, https://github.com/webrpc/webrpc/blob/3a0c9f0ee2f9eeda68b5fade4454c1a11791e94b/schema/ridl/parser.go#L334 we should be parsing the token value up until we reach a newline character

**Comment by xiam** [comment]
Is it possible to define a valid charset instead? I think we don’t want
spaces, tabs, or comments to be included.

**Comment by pkieltyka** [comment]
@xiam IMO, I think for the webrpc format, anything after to `=` up until `\n` should be considered a value value. We can't predict the contents people will want to pass to the generator. 

It looks like you wanted to have a more well defined format for the value so you can define a bunch of `+ go.tag.db = X + go.tag.db = Y` which is kinda cool, but IMO it's not worth it and we should use whitespace to help us with parsing and being more flexible, similar to YAML this way

**Comment by xiam** [comment]
If we can’t have a valid charset we can have a set of characters that
delimit the token, I think white space characters like space, tab, etc. are
fine and that should affect parsing of comments. What do you think?

**Comment by pkieltyka** [comment]
I think tab could work to delimit, but that is pretty much it, as some people might want space or other characters in their value, prob not tab or newline tho
