### ISSUE TITLE
Any way to generate "pointer" members?

### ISSUE THREAD

**Issue by hooksoft** [webrpc/webrpc#63]
A common pattern is to use pointers for values that might be null, say:
```
type Device struct {
	ID       int64
	DeviceID string `pg:",unique,notnull"`
	CreatedAt time.Time `pg:"default:now(),use_zero"`
	DeletedAt *time.Time
        ...
````
Could this make any sense in webrpc? 
Also, in general, shuold we reuse the types that webrpc-gen generates when dealing with the database/persistence side?

**Comment by pkieltyka** [comment]
@hooksoft yea looks good. 

If you want a pointer member, you have a few options. use `- field?: type` or use.. `- field: type` and then use `+ go.field.type = *time.Time` -- the `go.field.type` extension allows you to set any type you want, as a code-generator hint, an override essentially

**Comment by hooksoft** [comment]
How did I miss that... sorry for the noise.
