### ISSUE TITLE
Server/Client Hooks for Logging, Monitoring and Authorization

### ISSUE THREAD

**Issue by ansarizafar** [webrpc/webrpc#68]
Twirp has introduced support for client hooks in latest release https://github.com/twitchtv/twirp/releases for logging, monitoring and authorization.

Currently, we need to use a router and middle wares to perform above mentioned tasks on the server. I think the approach used by Twirp is much better, no need to use another package to provide routing/middleware on the server and hooks are also very useful on the client.

**Comment by pkieltyka** [comment]
hey @ansarizafar why do you say that the hooks pattern in Twirp is better than using a standard http middleware/handler stack? I'm curious why you think this.

WebRPC uses just standard http.Handler and middlewares (when it comes to Go). This is a far superior model as it means all of the http routers, middlewares and libraries that developers have built for their REST APIs and other microservices, are completely compatible with webrpc right now. This includes things like, logging, monitoring, auth, throttling, caching, exception handling, etc. etc.

Twirp hooks are in fact a major step backwards.

**Comment by ansarizafar** [comment]
I now realized, Yes, you are right.
