### ISSUE TITLE
Data validation constraints in schema

### ISSUE THREAD

**Issue by ansarizafar** [webrpc/webrpc#69]
It would be great, If we can define data validation constraints in schema for each message field and then generate code for validating message fields.

**Comment by pkieltyka** [comment]
This is out of the scope of WebRPC's responsibilities. We rely on the type-system for data type constraints, at an application-level you could implement a middleware, or in your data model, or in the rpc handler.

**Comment by ansarizafar** [comment]
You are right but It would be great, If Webrpc allow https://github.com/go-playground/validator validation tags to added to message fields. In this case, there is no need to generate any validation code just add these tags to generated struct and create, populate and pass the instance to rpc method.

````
webrpc = v1             # version of webrpc schema format (ridl or json)

name = example          # name if your backend app
version = v0.0.1        # version of your schema

message User
     - username: string
           + validation/rules = `validate:"required"`
    - email:string
           + validation/rules = `validate:"required,email"`


````

This will save developers to create a separate struct with validation tags, create an instance and populate. A single statement can be used to validate the generated type.

````
err := validate.Struct(user)
`````
