### ISSUE TITLE
CBOR for serialization 

### ISSUE THREAD

**Issue by ansarizafar** [webrpc/webrpc#71]
The Concise Binary Object Representation (CBOR) http://cbor.io/ is a data format whose design goals include the possibility of extremely small code size, fairly small message size, and extensibility without the need for version negotiation.

CBOR is based on the wildly successful JSON data model: numbers, strings, arrays, maps (called objects in JSON), and a few values such as false, true, and null. It has support for many languages.

Please consider CBOR for faster serialization.

**Comment by pkieltyka** [comment]
CBOR is pretty cool but browsers are optimized to parse JSON. Can you post a CBOR browser js library and some performance benchmarks?
