### ISSUE TITLE
Custom errors: Define API errors in RIDL

### ISSUE THREAD

**Issue by geokat** [webrpc/webrpc#72]
Would it be useful to be able to enumerate all possible errors for an API in the RIDL file?

This way API consumers could have a single place to learn everything they need to know about the API. Right now RIDL helps amazingly with that, except that it doesn't "contractualize" errors, so they have to be documented separately.

Also, it would be nice to be able to return multiple errors from an API. An example of an API that could benefit from this is an API that handles a form submission. Instead of returning errors one by one, it could include all of them in the first response so that the frontend can prompt the user to fix all of them before submitting the form again.

**Comment by pkieltyka** [comment]
Yea I agree. I’ll send another note later to add more thoughts on this, thanks for the feedback

**Comment by IvoPereira** [comment]
@pkieltyka any updates on this one?

I am looking for the exact same usecases as @geokat.

**Comment by VojtechVitek** [comment]
This feature is now available in webrpc@v0.11.0.

See https://github.com/webrpc/webrpc/blob/master/CHANGELOG.md#webrpc-v0110.
