### ISSUE TITLE
gen/ts always fails on empty response

### ISSUE THREAD

**Issue by jargv** [webrpc/webrpc#74]
If I have an rpc method like this...
```
  - Delete(id: string) => ()
```
... then the client always fails (after actually succeeding server-side) because the generated code looks like this:
```js
      return buildResponse(res).then(_data => {
        return {
        }
      })
```

And `buildResponse` always tries parse the JSON body, which is empty.

An easy workaround is to just return something from the rpc call: 
```
  - Delete(id: string) => (ok: boolean)
```
note: My server-side is Go and my client is TS.

**Comment by pkieltyka** [comment]
@jargv can you try the rpc definition as `- Delete(id: string)` and lmk how it works?

**Comment by jargv** [comment]
@pkieltyka `- Delete(id: string)` works the same as `- Delete(id: string) => ()`. If both syntaxes are supported, I would expect for the first to mean "no response body" and the second to mean "empty json object response body".

At any rate, whatever the server generates, the client should follow suit and not try to `JSON.parse` on an empty body.

**Comment by pkieltyka** [comment]
thx for heads up on this -- I have an upcoming release of webrpc that brings some new features which will also solve this issue

**Comment by VojtechVitek** [comment]
Fixed in [github.com/webrpc/gen-golang@v0.7.4](https://github.com/webrpc/gen-golang/releases/tag/v0.7.4).
