### ISSUE TITLE
Bidirectional rpc over websockets

### ISSUE THREAD

**Issue by vjpr** [webrpc/webrpc#86]
I’m looking for a bidirectional rpc over websockets. How tied to plain http transport is this lib?

Streaming would also be nice. But I see you already have an issue for it.

Also, did you consider using JSON-RPC standard? I am hesitant at the lock-in that comes from a custom rpc standard. Are there advantages of your protocol over this?

**Comment by VojtechVitek** [comment]
Webrpc streaming is now supported since v0.17.0. See https://github.com/webrpc/webrpc/releases.

If anyone feels strongly about websockets, please re-open the issue with more details/use-cases for `ws://`.
