### ISSUE TITLE
Go and TS, error type field missing "cause" in error type

### ISSUE THREAD

**Issue by pkieltyka** [webrpc/webrpc#93]
![image](https://user-images.githubusercontent.com/18831/120703895-e532be80-c483-11eb-81f5-fa2d99b9c5b7.png)

**Comment by pkieltyka** [comment]
will be solved in v0.8

**Comment by VojtechVitek** [comment]
Proposed solution from @kolberg-dev:

<img width="1361" alt="Screen Shot 2023-03-10 at 12 42 19 AM" src="https://user-images.githubusercontent.com/139342/224185593-018d37a1-de54-4d55-84a0-a38d5bdd06b1.png">

**Comment by pkieltyka** [comment]
btw, I've also written the Typescript code for error handling -- see below (you can ignore the other parts related to streaming)

* https://github.com/webrpc/webrpc/blob/next-streaming/_examples/golang-streaming/webapp/src/client.gen.ts#L387-L438
* https://github.com/webrpc/webrpc/blob/next-streaming/_examples/golang-streaming/webapp/src/main.ts#L46-L50

please follow my implementation, its very carefully crafted

**Comment by VojtechVitek** [comment]
This is fixed in current master (`v0.11.0-rc2`). Will be released as `v0.11.0` soon.

**Comment by VojtechVitek** [comment]
This is now available in [webrpc@v0.11.0](https://github.com/webrpc/webrpc/releases/tag/v0.11.0).
